### ISSUE TITLE
Unknown MySQL server host 'mysql'

### ISSUE THREAD

**Issue by memrekaraaslan** [hbceylan/vagrant-k8s-python#1]
Merhaba,

Azure Cloud üzerinde bir sunucu açarak projenizi bu VM'e clone ladım. Ardından da repo nun README sinde yazdığınız adımları uygulayarak python projesini ayağa kaldırdım. Sorunsuz bi şekilde 1 master 1 worker oalcak şekilde kubernetes cluster ı ayağa kalktı. Ardından da build.sh scriptini çalıştırırarak worker üzerinde python app i ve mysql app ini podlarda ayağa kaldırdım. kubectl ile bakıldığı zaman pod lar service ler deployment lar ve replicaset lerin hepsinin running pozisyonda olduğunu görüyorum. Fakat uygulamaya curl attığımda aşağıdaki gibi bi hata almaktayım. "Unknown MySQL server host 'mysql'" . Azure daki port rule larını da düzenledim. vagrant üzerinde oluşturduğumuz makinenin firewall u da kapalı onu da gördüm. Yani hiçbir engel göremedim fakat uygulamaya erişemiyorum. 
Logları attach files olarak ekliyorum: 
[mysql_error.txt](https://github.com/hbceylan/vagrant-k8s-python/files/7780201/mysql_error.txt)

[log.txt](https://github.com/hbceylan/vagrant-k8s-python/files/7780196/log.txt)

Yardımcı olursanız çok sevinirim.

**Comment by hbceylan** [comment]
Hi @memrekaraaslan ,

Everything looks fine according to the logs that you shared. Can you check the DNS pods of the cluster? Are they healthy? Is there any error log? Also, can you test by executing some `dig` or `nslookup` queries inside the application pod and share the output, please?

**Comment by memrekaraaslan** [comment]
Hello again @hbceylan 

As you said I execute the nslookup command and output is like that:

> vagrant@node-1:~$ kubectl exec -it hello-devops-5cfcb5b655-bnpzf -- nslookup kubernetes.default
;; connection timed out; no servers could be reached
command terminated with exit code 1

And the resolv.conf file inside the application pod looks like this:

> /app # cat /etc/resolv.conf
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local mr11qlnc4mduxjwoa5wvaczsvb.bx.internal.cloudapp.net
options ndots:5



I don't understand why the nslookup command is not working. I created dummy pod (dnsutil) but also I took the same error while execute the "kubectl exec -i -t dnsutils -- nslookup kubernetes.default" command

**Comment by memrekaraaslan** [comment]
By the way, I dont know this is important but I used flannel pod network instead of calico.  Because I got various errors when I tried to install Calico

applied this:
https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml


And I am working on Ubuntu 18.04.6 LTS

**Comment by hbceylan** [comment]
Hmm, looks like there is a network or DNS problem, not the application. 

So, you should fix this problem first and then will see the app will work as expected.

P.S: I don't know the exact problem of your AKS cluster but [nodelocaldns](https://kubernetes.io/docs/tasks/administer-cluster/nodelocaldns/) might help.

**Comment by memrekaraaslan** [comment]
Okay, thanks for your help.
